apiVersion: v1
kind: Secret
metadata:
  name: db-connection
type: Opaque
data:
  db_user: cG9zdGdyZXMuc2ZjaXV6anZob3Vmb3J3anZzbHc=
  db_password: MWhKSTBGRG5VMkc3eXVWUA==
  db_host: YXdzLTAtc2EtZWFzdC0xLnBvb2xlci5zdXBhYmFzZS5jb20=
  db_port: NjU0Mw==
  db_name: cG9zdGdyZXM=
