name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Pega os 7 primeiros dígitos do SHA do commit
      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      # Marketplace: Docker Login - os secrets estão nos 'settings' do repositório
      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Marketplace: Build and push Docker images
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            lucasnoman/nlw-journey-devops:${{ steps.generate_sha.outputs.sha }}
            lucasnoman/nlw-journey-devops:latest
